ACCESS_TOKEN: <your_access_token_here>
GROUP_ID: <your_group_id_here>
PROJECTS:
  - all:
    - <a_list_of_usernames_here>
  - <a_list_of_projects_here>
    - <a_list_of_usernames_here>
USERNAMES:
  - <a_list_of_usernames_here>
